users:
  - name: ${root_user}
    ssh_authorized_keys:
      - ${ssh_public_key}
    gecos: Cloud User
    groups: [ adm, systemd-journal ]
    sudo: [ "ALL=(ALL) NOPASSWD:ALL" ]
    shell: /bin/bash

  - name: ${docker_user}
    ssh_authorized_keys:
      - ${ssh_public_key}
    gecos: Cloud User
    groups: [ docker ]
    sudo: [ "ALL=(ALL) NOPASSWD:ALL" ]
    shell: /bin/bash

# If this is set, 'root' will not be able to ssh in and they
# will get a message to login instead as the default $user
disable_root: true


mount_default_fields: [ ~, ~, 'auto', 'defaults,nofail,x-systemd.requires=cloud-init.service,_netdev', '0', '2' ]
resize_rootfs_tmp: /dev

# Disable ssh password authentication
ssh_pwauth: false

# This will cause the set+update hostname module to not operate (if true)
preserve_hostname: false

# Default redhat settings:
ssh_deletekeys: true
ssh_genkeytypes: [ 'rsa', 'ecdsa', 'ed25519' ]
syslog_fix_perms: ~
disable_vmware_customization: false

# The modules that run in the 'init' stage
cloud_init_modules:
  - migrator
  - seed_random
  - bootcmd
  - write-files
  - growpart
  - resizefs
  - disk_setup
  - mounts
  - set_hostname
  - update_hostname
  - update_etc_hosts
  - ca-certs
  - rsyslog
  - users-groups
  - ssh

# The modules that run in the 'config' stage
cloud_config_modules:
  - ssh-import-id
  - locale
  - set-passwords
  - rh_subscription
  - spacewalk
  - yum-add-repo
  - ntp
  - timezone
  - disable-ec2-metadata
  - runcmd

# The modules that run in the 'final' stage
cloud_final_modules:
  - package-update-upgrade-install
  - write-files-deferred
  - puppet
  - chef
  - mcollective
  - salt-minion
  - reset_rmc
  - refresh_rmc_and_interface
  - rightscale_userdata
  - scripts-vendor
  - scripts-per-once
  - scripts-per-boot
  - scripts-per-instance
  - scripts-user
  - ssh-authkey-fingerprints
  - keys-to-console
  - install-hotplug
  - phone-home
  - final-message
  - power-state-change

# System and/or distro specific settings
# (not accessible to handlers/transforms)
locale: C.UTF-8
system_info:
  # This will affect which distro class gets used
  distro: rocky
  paths:
    cloud_dir: /var/lib/cloud/
    templates_dir: /etc/cloud/templates/
  ssh_svcname: sshd

# our configurations start here
bootcmd:
  - date > /etc/birth_certificate
  - sudo dnf update && sudo dnf upgrade-minimal -y
  - sudo dnf install dnf-automatic -y
  #  - sudo dnf install firewalld -y // for time being to install RKE
  - sudo dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo && sudo dnf -y install docker-ce containerd.io


timezone: Europe/London

write_files:
  - path: /etc/dnf/automatic.conf
    content: |
      [commands]
      upgrade_type = security
      random_sleep = 0
      network_online_timeout = 60
      download_updates = yes
      apply_updates = yes
      [emitters]
      emit_via = motd

  - path: /usr/lib/systemd/system/dnf-automatic-install.timer
    content: |
      [Unit]
      Description=dnf-automatic-install timer
      # See comment in dnf-makecache.service
      ConditionPathExists=!/run/ostree-booted
      Wants=network-online.target

      [Timer]
      OnCalendar=*-*-* 2:00
      RandomizedDelaySec = 0m
      Persistent=true

      [Install]
      WantedBy=timers.target

runcmd:
  - [ sudo, systemctl, --now, enable, dnf-automatic.timer ]
  #  - [ sudo, systemctl, --now, enable, firewalld ] // for time being to install RKE
  - [ sudo, systemctl, --now, enable, docker ]
